package com.jiangfeixiang.shopmiaosha.dao;

import com.jiangfeixiang.shopmiaosha.dataobject.UserDo;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    UserDo selectByPrimaryKey(Integer id);


    /**
     * 根据手机号查询
     * @param telphone
     * @return
     */
    UserDo selectByTelphone(String telphone);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Mar 02 13:04:55 CST 2019
     */
    int updateByPrimaryKey(UserDo record);
}