package com.jiangfeixiang.shopmiaosha.dataobject;

import java.math.BigDecimal;

public class ShopCartDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.user_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.item_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.title
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.imgUrl
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.price
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.totalPrice
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_cart.count
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.id
     *
     * @return the value of shop_cart.id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.id
     *
     * @param id the value for shop_cart.id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.user_id
     *
     * @return the value of shop_cart.user_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.user_id
     *
     * @param userId the value for shop_cart.user_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.item_id
     *
     * @return the value of shop_cart.item_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.item_id
     *
     * @param itemId the value for shop_cart.item_id
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.title
     *
     * @return the value of shop_cart.title
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.title
     *
     * @param title the value for shop_cart.title
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.imgUrl
     *
     * @return the value of shop_cart.imgUrl
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.imgUrl
     *
     * @param imgurl the value for shop_cart.imgUrl
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.price
     *
     * @return the value of shop_cart.price
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.price
     *
     * @param price the value for shop_cart.price
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.totalPrice
     *
     * @return the value of shop_cart.totalPrice
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.totalPrice
     *
     * @param totalprice the value for shop_cart.totalPrice
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_cart.count
     *
     * @return the value of shop_cart.count
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_cart.count
     *
     * @param count the value for shop_cart.count
     *
     * @mbg.generated Sun Mar 17 21:22:10 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}